initial floating ip association commit
hetznercloud/terraform-provider-hcloud pull request #8
Opened 2018-06-17 12:59 UTC by arminbuerkle

2018-06-17 13:11 UTC, arminbuerkle commented
@thetechnick didn't have much time the last days but here are finally the 2 PRs from the previous repo updated.

There still a bug in here which i couldn't quite figure out: 

When creating a floating_ip_association it shows the server and floating ip values as 0: 
```hcl
hcloud_floating_ip_association.test[0]
      id:             <computed>
      floating_ip_id: "0"
      server_id:      "0"
```

The result on remote and in the terraform.tfstate is correct though.

Similar when manually unassigning a server from a floating ip. A following `terraform plan` will show: 
```hcl
      server_id:      "123456" => "0"
``` 
A `terraform apply` will do the correct thing however.

2018-06-25 12:48 UTC, volym3ad commented
@thetechnick can you please review it?
This functionality is kinda necessary for me right now.

2018-08-20 10:36 UTC, LKDevelopment commented
@arminbuerkle would it be possible that you gave me an access to your repo?

2018-08-21 11:24 UTC, arminbuerkle commented
@LKDevelopment somehow your comment about access was lost. I just added you as a collaborator to the project.

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +	floatingIPID, ok := d.GetOk("floating_ip_id")
`floating_ip_id` is already required, no need to check it's set.

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +	serverID, ok := d.GetOk("server_id")
`server_id` is already required, no need to check it's set.

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +		log.Printf("[WARN] Floating IP Association ID (%s) not found, removing from state: %v", d.Id(), err)
Please change to `Floating IP ID (%s)`

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +	d.Set("server_id", server.ID)
use `floatingIP.Server.ID` here and negate the `if` on line 95

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +				Required: true,
We should mark this as `ForceNew` and remove the Update function

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +		log.Printf("[WARN] Floating IP Association ID (%s) not found, removing from state: %v", d.Id(), err)
This is not a `not found` error, but something along `invalid id` (similar to other resources)

2018-08-28 13:08 UTC, thetechnick commented on hcloud/resource_hcloud_floatingip_association.go
> +	floatingIP := &hcloud.FloatingIP{ID: floatingIPID.(int)}
Please change this to use the record id and not `floating_ip_id`.
So we do no longer have to validate `floating_ip_id`

2018-08-28 14:06 UTC, namxam commented
As there seems to be progress on this… any news on when to expect it to be available? This is quite critical for our setup and it would be nice if it makes sense to wait or if we have to find a "hack" to get it working.

2018-08-28 14:30 UTC, LKDevelopment commented
@namxam we plan to provide a new version within this or the next week.

2018-09-04 10:49 UTC, thcyron requested changes

2018-09-04 10:49 UTC, thcyron commented on CHANGELOG.md
> +* **New Resource**: `hcloud_floating_ip_association` Manage the association between floating ips and servers.
floating ips → Floating IPs

2018-09-04 10:49 UTC, thcyron commented on website/docs/r/floating_ip_association.html.md
> +- `floating_ip_id` - (Required) Id of the Floating IP.
Id → ID

2018-09-04 10:49 UTC, thcyron commented on website/docs/r/floating_ip_association.html.md
> +- `floating_ip_id` - Id of the Floating IP.
Id → ID

2018-09-04 10:49 UTC, thcyron commented on hcloud/resource_hcloud_floatingip_association.go
> +	_, _, err = client.FloatingIP.Unassign(ctx, floatingIP)
The API returns an error should the Floating IP already be unassigned. I think we should not treat that as an error.

Unfortunately, the API doesn’t return a dedicated error code in that case. I can take care of that to make the API return an error code à la `floating_ip_already_unassigned`.

2018-09-04 10:49 UTC, thcyron commented on CHANGELOG.md
> +* **New Resource**: `hcloud_floating_ip_association` Manage the association between floating ips and servers.
In the API we talk about assigning and unassigning Floating IPs. What about naming the resource `hcloud_floating_ip_assignment` then to be consistent?

2018-09-04 11:07 UTC, LKaemmerling commented on CHANGELOG.md
> +* **New Resource**: `hcloud_floating_ip_association` Manage the association between floating ips and servers.
This sounds good. I will update everything.

2018-09-06 12:22 UTC, merged